AppBundle\Entity\Personagem:
  type: entity
  table: personagem
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name: 
      type: string
      length: 45
      unique: true
    level:
      type: integer
      length: 3
    hpmax:
      type: integer
      length: 5
    hpcurrent:
      type: integer
      length: 5
    strength:
      type: integer
      length: 3
    defence:
      type: integer
      length: 3
    resistence:
      type: integer
      length: 3
      



